pretty-print = "always"
xml-namespace = true
continue-on-error = false

[macros]
d = "\\mathrm{d}"
bb = "\\mathbb{#1}"
foo = "x^2"

# [colors]
# sortaGreen = { format = "RGB", value = [ 128, 128, 0 ] }
