# release-plz configuration
# https://release-plz.dev/docs/config

[workspace]
changelog_update = false
git_release_enable = false
# Disable git tags for all packages by default
git_tag_enable = false

# Crates to publish (in dependency order)
[[package]]
name = "math-core-renderer-internal"
version_group = "math-core"
# Skip semver check for this package since it's internal and only meant to be used by other packages in the workspace.
semver_check = false

[[package]]
name = "math-core"
version_group = "math-core"
# Customize the git tag name to remove the `math-core` prefix.
git_tag_name = "v{{ version }}"
# Enable git tags for this package
git_tag_enable = true

[[package]]
name = "math-core-cli"
version_group = "math-core"
